
class Properties(object):
    """
    This class has the properties related to the PREDICATE annotations. Details can be found in the properties file. 
    """
    DELIMITER = "_"

    def __init__(self):
        self.properties = {
            "air_on" : [0],
            "air_until" : [1],
            "appear_in" : [2],
            "begin_at" : [3],
            "begin_in" : [4],
            "belong_to" : [5,6,7,8,9, 10, 11, 12],
            "boil_at": [13],
            "broadcast_on": [14],
            "canonize_in" : [15],
            "come_from" : [16, 17, 18],
            "command_during": [19],
            "debu_for": [20],
            "develop_from": [21],
            "die_on": [22],
            "die_in" :[23,24],
            "end_at": [25],
            "end_in": [26],
            "fight_in": [27],
            "flow_into": [28, 29, 30],
            "found_in": [31],
            "fuse_into": [32],
            "go_to": [33],
            "graduate_from": [34, 35],
            "intersect_with": [36],
            "live_in": [37],
            "marry_to": [38],
            "melt_at": [39],
            "operate_in": [40],
            "originate_in": [41, 42, 43],
            "play_for": [44, 47],
            "play_in": [45, 46, 48],
            "race_for": [49],
            "reside_in": [50],
            "rise_to": [51, 52],
            "run_into": [53, 54, 56],
            "run_under": [55],
            "serve_in": [57, 58, 59],
            "serve_under": [60],
            "stand_for": [61],
            "stand_at": [62],
            "study_at": [63, 64, 65],
            "sublime_at": [66],
            "work_on" : [67],
            "work_as": [68, 69]
        }

        self.DELIMITER = "_"
        self.ontologies_list = [
            ["http://dbpedia.org/ontology/channel", "first"],
            ["http://dbpedia.org/ontology/completionDate", "first"],
            ["http://dbpedia.org/ontology/guest", "last"],
            ["http://dbpedia.org/ontology/routeStart", "first"],
            ["http://dbpedia.org/ontology/routeStart", "first"],
            ["http://dbpedia.org/ontology/class", "first"],
            ["http://dbpedia.org/ontology/division", "first"],
            ["http://dbpedia.org/ontology/family", "first"],
            ["http://dbpedia.org/ontology/genus", "first"],
            ["http://dbpedia.org/ontology/kingdom", "first"],
            ["http://dbpedia.org/ontology/languageFamily", "first"],
            ["http://dbpedia.org/ontology/order", '"first'],
            ["http://dbpedia.org/ontology/phylum", "first"],
            ["http://dbpedia.org/ontology/boilingPoint", "first"],
            ["http://dbpedia.org/ontology/frequency", "first"],
            ["http://dbpedia.org/ontology/canonizedPlace", "first"],
            ["http://dbpedia.org/ontology/hometown", "first"],
            ["http://dbpedia.org/ontology/nationality", "first"],
            ["http://dbpedia.org/ontology/stateOfOrigin", "first"],
            ["http://dbpedia.org/ontology/commander", "last"],
            ["http://dbpedia.org/ontology/debutTeam", "first"],
            ["http://dbpedia.org/ontology/precursor", "first"],
            ["http://dbpedia.org/ontology/deathDate", "first"],
            ["http://dbpedia.org/ontology/deathPlace", "first"],
            ["http://dbpedia.org/ontology/deathYear", "first"],
            ["http://dbpedia.org/ontology/routeEnd", "first"],
            ["http://dbpedia.org/ontology/routeEnd", "first"],
            ["http://dbpedia.org/ontology/battle", "first"],
            ["http://dbpedia.org/ontology/mouthMountain", "first"],
            ["http://dbpedia.org/ontology/mouthPlace", "first"],
            ["http://dbpedia.org/ontology/riverMouth", "first"],
            ["http://dbpedia.org/ontology/foundationPlace", "first"],
            ["http://dbpedia.org/ontology/musicFusionGenre", "last"],
            ["http://dbpedia.org/ontology/education", "first"],
            ["http://dbpedia.org/ontology/almaMater", "first"],
            ["http://dbpedia.org/ontology/college", "first"],
            ["http://dbpedia.org/ontology/routeJunction", "first"],
            ["http://dbpedia.org/ontology/populationPlace", "first"],
            ["http://dbpedia.org/ontology/spouse", "first"],
            ["http://dbpedia.org/ontology/meltingPoint", "first"],
            ["http://dbpedia.org/ontology/regionServed", "first"],
            ["http://dbpedia.org/ontology/origin", "first"],
            ["http://dbpedia.org/ontology/source", "first"],
            ["http://dbpedia.org/ontology/sourceCountry", "first"],
            ["http://dbpedia.org/ontology/college", "first"],
            ["http://dbpedia.org/ontology/league", "first"],
            ["http://dbpedia.org/ontology/starring", "last"],
            ["http://dbpedia.org/ontology/team", "first"],
            ["http://dbpedia.org/ontology/tenant", "last"],
            ["http://dbpedia.org/ontology/team", "first"],
            ["http://dbpedia.org/ontology/residence", "first"],
            ["http://dbpedia.org/ontology/elevation", "first"],
            ["http://dbpedia.org/ontology/maximumElevation", "first"],
            ["http://dbpedia.org/ontology/mouthMountain", "first"],
            ["http://dbpedia.org/ontology/mouthPlace", "first"],
            ["http://dbpedia.org/ontology/operatingSystem", "first"],
            ["http://dbpedia.org/ontology/riverMouth", "first"],
            ["http://dbpedia.org/ontology/battle", "first"],
            ["http://dbpedia.org/ontology/militaryBranch", "first"],
            ["http://dbpedia.org/ontology/militaryUnit", "first"],
            ["http://dbpedia.org/ontology/president", "first"],
            ["http://dbpedia.org/ontology/callsignMeaning", "first"],
            ["http://dbpedia.org/ontology/elevation", "first"],
            ["http://dbpedia.org/ontology/almaMater", "first"],
            ["http://dbpedia.org/ontology/education", "first"],
            ["http://dbpedia.org/ontology/university", "first"],
            ["http://dbpedia.org/ontology/sublimationPoint", "first"],
            ["http://dbpedia.org/ontology/field", "first"],
            ["http://dbpedia.org/ontology/occupation", "first"],
            ["http://dbpedia.org/ontology/profession", "first"],
        ]
